#!/bin/zsh

$BIN_DIR=$HOME/.local/bin

. $BIN_DIR/lib/env_os.sh

# if is_wsl; then
#     # SSH by Host(Windows)
#     alias ssh='ssh.exe'
#     alias ssh-add='ssh-add.exe'
# fi

# パッケージのアップデートコマンド
alias pup=$BIN_DIR/mng/pkg_update

# パッケージのインストールコマンド
alias pins=$BIN_DIR/mng/pkg_install

# Create package list
alias pdump=$BIN_DIR/mng/pkg_dump

# Print dotfiles structure
alias pstr=$BIN_DIR/struct/print_struct
