#!/bin/zsh

source ~/dotfiles/lib/env

# if is_wsl; then
#   # SSH by Host(Windows)
#     alias ssh='ssh.exe'
#     alias ssh-add='ssh-add.exe'
# fi

# パッケージのアップデートコマンド
alias pupd='~/dotfiles/bin/mng/pkg_update'

# パッケージのインストールコマンド
alias pinstall='~/dotfiles/bin/mng/pkg_install'

# Create package list
alias pdump='~/dotfiles/bin/mng/pkg_dump'

# Print dotfiles structure
alias pstr='~/dotfiles/bin/struct/print_struct'