name: CI

on:
  push:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Install required packages
        run: apt-get update && apt-get install -y curl
      - name: Install dotfiles
        run: bash -c "$( curl -fsSL https://raw.github.com/${github-username}/dotfiles/master/setup.sh )"

  centos:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - name: Install required packages
        run: yum install -y curl
      - name: Install dotfiles
        run: bash -c "$( curl -fsSL https://raw.github.com/${github-username}/dotfiles/master/setup.sh )"

  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install required packages
        run: apk add git sudo bash curl
      - name: Install dotfiles
        run: bash -c "$( curl -fsSL https://raw.github.com/${github-username}/dotfiles/master/setup.sh )"

  arch:
    runs-on: ubuntu-latest
    container: archlinux/base:latest
    steps:
      - name: Update packages
        run: pacman -Syu --noconfirm
      - name: Install required packages
        run: pacman -S --noconfirm sudo bash curl
      - name: Install dotfiles
        run: bash -c "$( curl -fsSL https://raw.github.com/${github-username}/dotfiles/master/setup.sh )"
  macos:
    runs-on: macos-latest
    steps:
      - name: Install dotfiles
        run: bash -c "$( curl -fsSL https://raw.github.com/${github-username}/dotfiles/master/setup.sh )"

  win-install:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "Hello from Windows!"

  lint:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - name: Update packages
        run: apt-get update
      - name: Install packages for install repository
        run: apt-get install -y git sudo software-properties-common
      - name: Install required repository
        run: apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe"
      - name: Install required packages
        run: apt-get update; apt-get install -y shellcheck
      - name: Execute shellcheck
        run: test $(shellcheck  -f gcc ~/.zshrc ~/.zsh/rc/* | grep -v "SC1036\|SC1056\|SC1070\|SC1072\|SC1073\|SC1083\|SC2034\|SC2139\|SC2148\|SC1090\|SC1117\|SC2206\|SC1009\|SC2016\|SC2046\|SC2154" | tee -a /dev/stderr | wc -l) -le 1
