[tools]
# no dependency
erlang = "latest"
deno = "latest"
dotnet = "latest"
go = "latest"
java = "latest"
python = "latest"
rust = "latest"

# Dependency
elixir = "latest"
flutter = "latest"
kotlin = "latest"

# Rubyインストールの依存関係
# https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
# apt-get install build-essential autoconf libssl-dev libyaml-dev zlib1g-dev libffi-dev libgmp-dev rustc
ruby = "latest"
