[tools]
# no dependency
erlang = "latest"
deno = "latest"
dotnet = "latest"
go = "latest"
java = "latest"
python = "latest"
rust = "latest"

# Dependency
elixir = "latest"
flutter = "latest"
kotlin = "latest"
ruby = "latest" # required 'libyaml'
android-sdk = "latest"
